#!/bin/sh

XORG_CONF_DIR="/etc/X11/xorg.conf.d"

NVIDIA_CONF="$XORG_CONF_DIR/10-nvidia-gpu.conf"
NVIDIA_CONF_DIS="$XORG_CONF_DIR/10-nvidia-gpu.conf.dis"

if [ $# -ne 1 ]; then
    echo "usage: set-gpu [on|off]"
    exit 1
fi

# AC
if [ $1 = "on" ]; then
    if [ -f "$NVIDIA_CONF_DIS" ]; then
        echo "Enabling NVIDIA GPU."
        mv "$NVIDIA_CONF_DIS" "$NVIDIA_CONF"
    else
        echo "GPU is already enabled"
    fi
elif [ $1 = "off" ]; then
    if [ -f "$NVIDIA_CONF" ]; then
        echo "Disabling NVIDIA GPU."
        mv "$NVIDIA_CONF" "$NVIDIA_CONF_DIS"
    else
        echo "GPU already disabled."
    fi
else
    echo "usage: set-gpu [on|off]"
    exit 1
fi


